# Generated by Django 5.2.15 on 2026-06-17 12:18

import django.db.models.deletion
import othello_web.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GameSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "opponent_type",
                    models.CharField(
                        choices=[("ai", "AI"), ("random", "Random")], max_length=20
                    ),
                ),
                (
                    "user_color",
                    models.IntegerField(choices=[(1, "Black"), (-1, "White")]),
                ),
                (
                    "current_board",
                    models.JSONField(
                        validators=[othello_web.models.validate_board_format]
                    ),
                ),
                (
                    "current_turn",
                    models.IntegerField(choices=[(1, "Black"), (-1, "White")]),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("playing", "Playing"),
                            ("finished", "Finished"),
                            ("abandoned", "Abandoned"),
                        ],
                        default="playing",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MatchHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "opponent_type",
                    models.CharField(
                        choices=[("ai", "AI"), ("random", "Random")], max_length=20
                    ),
                ),
                (
                    "result",
                    models.CharField(
                        choices=[("win", "Win"), ("loss", "Loss"), ("draw", "Draw")],
                        max_length=20,
                    ),
                ),
                ("played_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
